source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'YandexMobileAdsProxy' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks! :linkage => :static

  # Pods for YandexMobileAdsProxy
  pod 'YandexMobileAds', '7.8.0'

end
